### PR TITLE
Entity spawning (WIP do not merge)

### PR DESCRIPTION
**Pull request by kozr**
We're merging these commits into dev after a review or two. Give me some time to check over this code too.

### CODE REVIEW

**Comment by kozr** [comment]
I tested out the feature, it's pretty good but let me try to set it to spawn to near its building first. I'll keep this pull request on but don't merge it yet.

**Comment by kozr** [comment]
I've also disabled force merge and every merge request now require at least one person to review it. I didn't set it up properly yesterday.

**Comment by adrianlamcw** [comment]
If you don't know what's going on in the code, let me know because I wrote the part about igm and clicking update.

**Comment by kozr** [comment]
We'll leave entity spawning alone until we've potentially refactored it into an abstract class that other classes can extend to.

**Pull request closed without merging**
